project_id = "ziswkjqnjwhcbutcglfr"

[functions.rafiq-chat]
verify_jwt = false

[functions.speech-analysis]
verify_jwt = false

[functions.kanji-ocr]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.manage-sessions]
verify_jwt = false
